### ISSUE TITLE
Got-Error while using example query

### ISSUE THREAD

**Issue by MPRR-Pandu** [bytebase/example-gitops-github-flow#15]
Error: failed to check release, error: proto: (line 1:94): invalid value for bytes field statement: "CREATE TABLE IF NOT EXISTS ticket (\n  id int,\n  name text\n);\n"

```
CREATE TABLE IF NOT EXISTS ticket (
  id int,
  name text
);
```

```
 - name: Check release
        uses: bytebase/create-release-action@v1.0.4
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          file-pattern: ${{ env.FILE_PATTERN }}
          # fail the action if release checks report any error.
          check-release: "FAIL_ON_ERROR"
          project: ${{ env.BYTEBASE_PROJECT }}
          targets: ${{ env.BYTEBASE_TARGETS }}
          validate-only: true

```
